title: Vector Overlay Concepts
description: Visualizing GIS logic with ArcPy.
remote_theme: just-the-docs/just-the-docs

# Navigation Settings
nav_external_links:
  - title: GitHub Repo
    url: https://github.com/def-fun7/vector_overlay_gis

# Enable Math
math: mathjax

# Search settings
search_enabled: true
favicon_ico: "assets/gis.ico"